# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $user: '%env(string:MQTT_USER)%'
            $password: '%env(string:MQTT_PASSWORD)%'
            $host: '%env(string:MQTT_HOST)%'
            $port: '%env(int:MQTT_PORT)%'
            $keepAliveInterval: 60

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    SupremeMqtt\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    SupremeMqtt\EventListener\MqttListener:
        tags:
            - { name: kernel.event_listener, event: event.message.received }

    SupremeMqtt\Client\MqttClient:
        arguments:
            $user: '%env(string:MQTT_USER)%'
            $password: '%env(string:MQTT_PASSWORD)%'
            $host: '%env(string:MQTT_HOST)%'
            $port: '%env(int:MQTT_PORT)%'
            $keepAliveInterval: 60

    SupremeMqtt\Service\MqttClientService:
        arguments:
            $mqttClient: '@SupremeMqtt\Client\MqttClient'
            $mqttListener: '@SupremeMqtt\EventListener\MqttListener'
            $eventDispatcher: '@event_dispatcher'

    SupremeMqtt\Command\WatchMessagesCommand:
        arguments: ['@SupremeMqtt\Service\MqttClientService']
        tags:
            - { name: console.command }
